### PR TITLE
Mutual TLS

### PR DESCRIPTION
**Pull request by stefano-ottolenghi**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-drivers-445.surge.sh

Updated pages:
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/python-manual/5/connect-advanced)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-drivers-445.surge.sh

Updated pages:
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/go-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/python-manual/5/connect-advanced)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-drivers-445.surge.sh

Updated pages:
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/go-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/javascript-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/python-manual/5/connect-advanced)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-drivers-445.surge.sh

Updated pages:
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/go-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/javascript-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/python-manual/5/connect-advanced)

**Review by robsdedude — APPROVED** [review]
:closed_lock_with_key:

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-drivers-445.surge.sh

Updated pages:
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/go-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/java-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/javascript-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/python-manual/5/connect-advanced)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-drivers-445.surge.sh

Updated pages:
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/go-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/java-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/javascript-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/python-manual/5/connect-advanced)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-drivers-445.surge.sh

Updated pages:
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/go-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/java-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/javascript-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/python-manual/5/connect-advanced)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-drivers-445.surge.sh

Updated pages:
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/go-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/java-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/javascript-manual/5/connect-advanced)
- [Advanced connection information](https://neo4j-docs-drivers-445.surge.sh/python-manual/5/connect-advanced)

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Pull request merged**
