### PR TITLE
Add GraphAcademy promo block

### PR DESCRIPTION
**Pull request by adam-cowley**
Depends on https://github.com/neo4j-documentation/docs-ui/pull/234

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-drivers-433.surge.sh

Updated pages:
- [Build applications with Neo4j and Python](https://neo4j-docs-drivers-433.surge.sh/python-manual/5)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-drivers-433.surge.sh

Updated pages:
- [Build applications with Neo4j and Python](https://neo4j-docs-drivers-433.surge.sh/python-manual/5)

**Review by recrwplay — APPROVED** [review]

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Review by recrwplay — APPROVED** [review]

**Comment by stefano-ottolenghi** [comment]
My take is that we should clarify what we want these promos to communicate to users. 
Do we want people to take the course:

1. _before_ reading docs, and then coming back to docs? 
2. _after_ having read docs, as a hands-on experience? Maybe after having read a _part_ of docs?
3. as an _alternative_ to docs? 

As the promo is placed now, we are promoting option 3. I don't think it's the right one. The message users get from this is "hey here is a shiny course, you shouldn't be here at all! Go here!" And then users face the choice: do they ignore the banner, or do they follow it? 

- If they decide to ignore it, they may also feel entitled to ignore other content in the manual, because as soon as you distrust _a bit_ of something, you feel entitled to distrust _however much_ you want (it is a psychological phenomenon). And if they ignore it, why is it there at all?
- If they follow it, why did they land on the manual in the first place? They will just think they were in the wrong place. But were they? 

Dropping a shiny promo on all pages is not a service to users: they are not qualified (yet) to decide which resource they should entrust for their initial exploration. Overwhelming them with choice is likely to have the counterproductive effect of branching their attention and giving them the impression that we haven't carefully planned their learning journey.

We should ponder more about how docs and GA course should complement each other before throwing there a banner.
There is tremendous value in a hands-on course as GA provides, and we should direct users there as a way of completing a project and getting some practical experience _after_ they've read the first few docs pages. I don't think the GA course is a replacement of docs, nor that it should be. However, that's what it currently tries to do: it provides a lot of details on things of less importance for a hands-on project (like the neo4j URI schemes or all cypher types), while at the same time lacking in some parts (no execute_query, for ex). It mixes reference docs and practical bits, so it's not clear what users should do with the two resources. 

For a long time the driver manuals have not been beginner-friendly, but today the situation is different. When I re-did the manuals, I purposefully put GA courses links at the bottom of the left sidebar because that's when it makes sense for people to leave docs and do something practical: after you've stitched together a few examples, have a running neo4j server and a faint idea of what's happening, then go do all relevant GA courses. 
Also notice that the `Create applications` page is the single most visited docs page, and it's fair to assume that a large percentage of those visiting that (and thus driver manuals) are not cypher ninjas. That's why I've put links to cypher GA courses as well. 
When you feel like you've exhausted topics you want to know about, there's for your links to to hands-on projects. (And yes, that section should be named `Hands-on courses` and not `Graphacademy courses`.)

I believe we should focus the GA course more on the practical part and leave out all the reference material, and identify the best (one) place in the manual to sort of "graduate users" from the docs and into GA. I don't support the choice of putting it on all pages (including the bottom of the intro).

**Pull request closed without merging**
