### PR TITLE
Update temporal type names

### PR DESCRIPTION
**Pull request by injectives**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-drivers-399.surge.sh

**Comment by stefano-ottolenghi** [comment]
Thanks Dmitriy! Core types were also updated - I believe everything is basically uppercase now, but worth double checking. Do you have time to update those as well? My reference is this:
https://github.com/neo4j/docs-cypher/pull/596/files

**Review by michael-simons — APPROVED** [review]
Thanks.

**Comment by michael-simons** [comment]
They are case insensitive @stefano-ottolenghi 

Here, they actual type names changed.

**Comment by stefano-ottolenghi** [comment]
> They are case insensitive @stefano-ottolenghi

Fair, but

- cypher docs were painstakingly updated everywhere to have them uppercase, including core types
- `Duration` and `Date` were updated in this PR, even though only the case has changed.

Some consistency would be appreciated by readers. Nowhere it's written that types are case insensitive, and if I see `Point` in one set of docs and `POINT` in another, as a user I would be right in wondering/questioning whether they are the same type ... and complaining if indeed they do.

**Comment by injectives** [comment]
> Thanks Dmitriy! Core types were also updated - I believe everything is basically uppercase now, but worth double checking. Do you have time to update those as well? My reference is this: https://github.com/neo4j/docs-cypher/pull/596/files

Thanks! I can try updating in a separate PR.

**Comment by injectives** [comment]
@stefano-ottolenghi, opened #400.

**Pull request merged**
