### PR TITLE
Update 5.0 to Antora package

### PR DESCRIPTION
**Pull request by recrwplay**
See #295 for details

### CODE REVIEW

**Review by davidoliverSP2 — CHANGES_REQUESTED** [review]
It seems that the TOC is not building on each of the manuals
Screenshot 2022-08-25 at 13 27 27

**Comment by davidoliverSP2** [comment]
Error message:
```
[13:13:21.123] ERROR (asciidoctor): target of xref not found: operations-manual.adoc#config_dbms.default_advertised_address
    file: /Users/davidoliver/Git/neo4j/driver-documentation/dotnet-manual/modules/ROOT/pages/client-applications.adoc
    source: /Users/davidoliver/Git/neo4j/driver-documentation (branch: 5.0-antora-migration <worktree> | start path: dotnet-manual)
[13:13:21.547] ERROR (asciidoctor): target of xref not found: operations-manual.adoc#config_dbms.default_advertised_address
    file: /Users/davidoliver/Git/neo4j/driver-documentation/go-manual/modules/ROOT/pages/client-applications.adoc
    source: /Users/davidoliver/Git/neo4j/driver-documentation (branch: 5.0-antora-migration <worktree> | start path: go-manual)
[13:13:21.855] ERROR (asciidoctor): target of xref not found: operations-manual.adoc#config_dbms.default_advertised_address
    file: /Users/davidoliver/Git/neo4j/driver-documentation/java-manual/modules/ROOT/pages/client-applications.adoc
    source: /Users/davidoliver/Git/neo4j/driver-documentation (branch: 5.0-antora-migration <worktree> | start path: java-manual)
[13:13:22.225] ERROR (asciidoctor): target of xref not found: operations-manual.adoc#config_dbms.default_advertised_address
    file: /Users/davidoliver/Git/neo4j/driver-documentation/javascript-manual/modules/ROOT/pages/client-applications.adoc
    source: /Users/davidoliver/Git/neo4j/driver-documentation (branch: 5.0-antora-migration <worktree> | start path: javascript-manual)
[13:13:22.613] ERROR (asciidoctor): target of xref not found: operations-manual.adoc#config_dbms.default_advertised_address
    file: /Users/davidoliver/Git/neo4j/driver-documentation/python-manual/modules/ROOT/pages/client-applications.adoc
    source: /Users/davidoliver/Git/neo4j/driver-documentation (branch: 5.0-antora-migration <worktree> | start path: python-manual)
```

**Comment by recrwplay** [comment]
> It seems that the TOC is not building on each of the manuals

Oops. Gradle copy task didn't include the nav files. Now fixed.

**Comment by recrwplay** [comment]
> config_dbms.default_advertised_address

Broken xrefs replaced with `link:`

**Review by davidoliverSP2 — APPROVED** [review]

**Comment by davidoliverSP2** [comment]
Looks good now, thanks @recrwplay 🎉

**Pull request merged**
