### PR TITLE
Adding examples for Python's temporal types

### PR DESCRIPTION
**Pull request by robsdedude**
Depending on https://github.com/neo4j/neo4j-python-driver/pull/616

Should also be backported to 4.3, once https://github.com/neo4j/neo4j-python-driver/pull/617 has been merged.

### CODE REVIEW

**Comment by davidoliverSP2** [comment]
@robsdedude do you know whether temporal types are only going to be supported by the Python driver?

**Comment by robsdedude** [comment]
@davidoliverSP2 no. All drivers should offer support. There were PRs for JS already: https://github.com/neo4j/driver-documentation/pull/228 among others.

**Comment by robsdedude** [comment]
@davidoliverSP2 required PRs merged now. Ready for review.

**Review by davidoliverSP2 — APPROVED** [review]
Looks good, thanks @robsdedude

**Pull request merged**
