### PR TITLE
Adding a section and example on how to use multiple transactions with…

### PR DESCRIPTION
**Pull request by gjmwoods**
Adding a section and example on how to use multiple transactions within a single asynchronous session

### CODE REVIEW

**Review by davidoliverSP2 — APPROVED** [review]
Thanks @gjmwoods 

This builds well using the single source copy. I've not yet been able to generate the example code though.

**Comment by davidoliverSP2** [comment]
@gjmwoods is this still work in progress?

**Comment by gjmwoods** [comment]
@davidoliverSP2 yeah still in progress. Just waiting for the .NET example: https://trello.com/c/W5teZer8

**Comment by gjmwoods** [comment]
@davidoliverSP2 Just picking this up again. .NET has been merged now

**Pull request merged**
