### PR TITLE
Adding a common section on configuration options that can be provide…

### PR DESCRIPTION
**Pull request by gjmwoods**
…d to transactions

### CODE REVIEW

**Review by bigmontz — APPROVED** [review]
🥇

**Comment by gjmwoods** [comment]
image
image

**Review by davidoliverSP2 — CHANGES_REQUESTED** [review]
@gjmwoods Thanks, and apologies for the slow review.

All the manuals for each language look good, but the Python manual is generating the code examples: 
Screenshot 2021-10-20 at 16 36 02

Could you (or @bigmontz) take a look at the Python includes to see if they're marked up correctly, and in the published 4.2 Python Driver?

**Comment by gjmwoods** [comment]
@davidoliverSP2 I think the python examples should be fixed now

**Review by davidoliverSP2 — APPROVED** [review]

**Comment by davidoliverSP2** [comment]
Thanks @gjmwoods 

This all looks good, but there are some merge conflicts to resolve - could you take a look, and when the PR is green, I'm happy to merge & cherrypick forward.

**Pull request merged**
